# Generated by Django 5.2.1 on 2025-06-06 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField()),
                ('num_serie', models.CharField()),
                ('descripcion', models.CharField()),
                ('numero', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('dni', models.CharField()),
                ('correo', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField()),
                ('Computadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.computadora')),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.curso')),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.estudiante')),
            ],
        ),
    ]
